#include <stdio.h>

/* Generated by the SConstruct from the flavour SCons was given, so an archive
   carrying a program built with the WRONG flavour fails the journey's
   assertion instead of passing it silently. The flavour reaches the
   SConstruct from the build option's scons_args and from nowhere else. */
#include "dslp_flavour.h"

int main(void) {
    printf("%s %s\n", "dslp sconsproof ok", DSLP_FLAVOUR);
    return 0;
}
// webhook-build push f8fc92d99d1ace7f
// webhook-build push 0b60ad1696b4c553
// webhook-build push 58b89f8ec362d958
// webhook-build push 2b523508d2628f58
// webhook-build push c7b59f1657b7f802
// webhook-build push 4140910156a561e6
// webhook-build push abd1c470c45a1654
// webhook-build push 6c92d6abd7d00e16
// webhook-build push 366ba434cef3cc56
// webhook-build push 424ea7d31ca53b21
// webhook-build push 4373cb2504bc342d
// webhook-build push af6ad758a069f793
// webhook-build push 82d7dd4fa371f3bd
// webhook-build push f37206af764558f1
// webhook-build push d62ed6ed4cd87320
// webhook-build push 0ce0c760d4115d67
// webhook-build push 711e04b784b7729d
// webhook-build push 153ed976c040ab9d
// webhook-build push 9c5bd15f4f539afb
// webhook-build push ef0feb0819e39bca
// webhook-build push 1c5e1a5b992f87b3
// webhook-build push 85cc7734c5dd5f60
// webhook-build push 28e5885bbd98a5a8
// webhook-build push 71262034a256b639
// webhook-build push 7ea6c353767846c9
// webhook-build push 3314577345c5b749
