#include <stdio.h>

/* Generated by the SConstruct from the flavour SCons was given, so an archive
   carrying a program built with the WRONG flavour fails the journey's
   assertion instead of passing it silently. The flavour reaches the
   SConstruct from the build option's scons_args and from nowhere else. */
#include "dslp_flavour.h"

int main(void) {
    printf("%s %s\n", "dslp sconsproof ok", DSLP_FLAVOUR);
    return 0;
}
