#include <stdio.h>

/* Generated by the SConstruct from the flavour SCons was given, so an archive
   carrying a program built with the WRONG flavour fails the journey's
   assertion instead of passing it silently. The flavour reaches the
   SConstruct from the build option's scons_args and from nowhere else. */
#include "dslp_flavour.h"

int main(void) {
    printf("%s %s\n", "dslp sconsproof ok", DSLP_FLAVOUR);
    return 0;
}
// webhook-build push f8fc92d99d1ace7f
// webhook-build push 0b60ad1696b4c553
// webhook-build push 58b89f8ec362d958
// webhook-build push 2b523508d2628f58
// webhook-build push c7b59f1657b7f802
// webhook-build push 4140910156a561e6
